// <auto-generated />
namespace MvcFormsAuthentication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MD5Password : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MD5Password));
        
        string IMigrationMetadata.Id
        {
            get { return "201905191655019_MD5Password"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
